name: CI

on: [pull_request]

concurrency:
  group: ci-${{ github.event.pull_request.title }}
  cancel-in-progress: true

jobs:
  lint-styles:
    name: Lint Styles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm run lint
